const HUGGING_FACE_MODELS = [
    {
      name: 'RoBERTa Base OpenAI Detector',
      url: 'openai-community/roberta-base-openai-detector',
      description: 'This model utilizes the RoBERTa base architecture to detect text generated by AI systems. It is particularly calibrated to identify nuances in text that may suggest artificial generation, leveraging the robust training and generalization capabilities of the RoBERTa base model.',
      type: 'detect'
    },
    // {
    //   name: 'RoBERTa Large OpenAI Detector',
    //   url: 'openai-community/roberta-large-openai-detector',
    //   description: 'Larger than its base counterpart, this model employs the RoBERTa large architecture for enhanced detection of AI-generated text. Its increased model size allows for better understanding and identification of complex patterns in synthetic text, making it highly effective for academic and commercial applications where discerning human-like text is critical.',
    //   type: 'detect'
    // },
    {
      name: 'AI-HUMAN-detector',
      url: 'idajikuu/AI-HUMAN-detector',
      description: 'Designed to discern between AI-generated and human-generated content, this model provides a tool for users needing to verify the authenticity of digital text. Although specific details are sparse, users can explore its capabilities further on its Hugging Face repository page.',
      type: 'detect'
    },
    // {
    //   name: 'The AIGC Detector (clicky clicky)',
    //   url: 'yuchuantian/AIGC_detector_zhv2',
    //   description: 'The AIGC (AI-Generated Content) Detector employs a Multiscale Positive-Unlabeled (MPU) approach for the detection of AI-generated texts as described in the associated paper. It emphasizes the use of multiple scales of analysis to improve detection accuracy, making it suitable for a variety of applications, from moderating online content to ensuring the integrity of informational publications.',
    //   type: 'detect'
    // },
    {
      name: 'Detector for AI-generated Text (clicky clicky)',
      url: 'microsoft/DialoGPT-medium',
      description: 'This medium-sized model from Microsofts DialoGPT series is specifically trained to detect AI-generated dialogues and conversations.',
      type: 'chat'
    },
    {
      name: 'Mistral-7B-Instruct',
      url: 'mistralai/Mistral-7B-Instruct-v0.2',
      description:'testing a chat model',
      type: 'instruct'
    }
  ];
  
  
  export default HUGGING_FACE_MODELS;